services:
  # stacks-blockchain-api instance
  - name: mocknet-stacks-blockchain-api
    type: pserv
    env: docker
    region: oregon
    plan: Standard
    branch: mocknet
    dockerfilePath: stacks-blockchain-api.Dockerfile
    dockerContext: .
    autoDeploy: false
    envVars:
      - key: PG_HOST
        fromService:
          name: mocknet-postgres
          type: pserv
          property: host
      - key: PG_PORT
        value: 5432
      - key: PG_DATABASE
        value: postgres        
      - key: PG_USER
        value: postgres
      - key: STACKS_CORE_EVENT_HOST
        value: 0.0.0.0
      - key: STACKS_BLOCKCHAIN_API_HOST
        value: 0.0.0.0
      - key: STACKS_BLOCKCHAIN_API_DB
        value: pg
      - key: STACKS_CORE_RPC_HOST
        fromService:
          name: mocknet-stacks-blockchain
          type: pserv
          property: host
      - key: STACKS_CORE_RPC_PORT
        value: 80
      - fromGroup: mocknet-settings

  # stacks-blockchain instance
  - name: mocknet-stacks-blockchain
    type: pserv
    env: docker
    region: oregon
    plan: Standard
    branch: mocknet
    dockerfilePath: stacks-blockchain.Dockerfile
    dockerContext: .
    autoDeploy: false 
    envVars:
      - key: STACKS_BLOCKCHAIN_API_HOST
        fromService:
          name: mocknet-stacks-blockchain-api
          type: pserv
          property: host
      - fromGroup: mocknet-settings

  # nginx proxy instance
  - name: mocknet-nginx
    type: web
    env: docker
    region: oregon
    plan: Standard
    branch: mocknet
    dockerfilePath: nginx.Dockerfile
    dockerContext: .
    healthCheckPath: /status
    autoDeploy: true
    envVars:
      - key: STACKS_BLOCKCHAIN_API_HOST
        fromService:
          name: mocknet-stacks-blockchain-api
          type: pserv
          property: host
      - fromGroup: mocknet-settings


  # Private Postgres instance
  - name: mocknet-postgres
    type: pserv
    env: docker
    region: oregon
    plan: standard
    branch: mocknet
    dockerfilePath: postgres.Dockerfile
    autoDeploy: false
    envVars:
      - fromGroup: mocknet-settings


envVarGroups:
  - name: mocknet-settings
    envVars:
      - key: NODE_ENV
        value: production
      - key: GIT_TAG
        value: master
      - key: STACKS_CHAIN_ID
        value: 2147483648
      - key: V2_POX_MIN_AMOUNT_USTX
        value: 90000000260
      - key: STACKS_NETWORK
        value: mocknet
      - key: STACKS_CORE_EVENT_PORT
        value: 3700
      - key: STACKS_BLOCKCHAIN_API_PORT
        value: 3999
      - key: POSTGRES_PASSWORD
        value: postgres
