services:
  - name: mainnet_e_reader
    type: web
    env: docker
    region: oregon
    plan: Pro
    branch: mainnet-read-write
    dockerfilePath: stacks-blockchain-api.Dockerfile
    dockerContext: .
    autoDeploy: false
    envVars:
      - fromGroup: mainnet_d_reader_config
  - name: mainnet_f_reader
    type: web
    env: docker
    region: oregon
    plan: Pro
    branch: mainnet-read-write
    dockerfilePath: stacks-blockchain-api.Dockerfile
    dockerContext: .
    autoDeploy: false
    envVars:
      - fromGroup: mainnet_d_reader_config

